Add vifdump support for interface names (vif0/1 or mon2) and sudo. Disable IPv6 on the monitoring interface.

diff --git a/utils/vifdump b/utils/vifdump
--- a/utils/vifdump
+++ b/utils/vifdump
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 ##
-## vRouter/DPDK tcpdump
+## vRouter/DPDK vif tcpdump
 ##
 
 ## Constants
@@ -12,17 +12,17 @@ MON_TYPE="monitoring"
 usage () {
     echo "vRouter/DPDK vif tcmpdump script"
     echo "Usage:"
-    echo "      ${0##*/} <vif index> [tcpdump arguments]"
+    echo "      ${0##*/} [-i] <vif> [tcpdump arguments]"
     echo "              - to run tcpdump on a specified vif"
-    echo "      ${0##*/} stop <vif index>"
-    echo "              - to force stop the monitoring and clean up the vif specified"
+    echo "      ${0##*/} stop <monitoring_if>"
+    echo "              - to force stop and clean up the monitoring interface"
     echo "Example:"
-    echo "      ${0##*/} 1 -nvv"
+    echo "      ${0##*/} -i vif0/1 -nvv"
     exit 1
 }
 
 error () {
-    echo -e "${0##*/} error: $1"
+    echo "${0##*/} error: $1"
     exit 1
 }
 
@@ -30,8 +30,10 @@ monitoring_stop () {
     if [ $# -lt 1 ]; then
         usage
     fi
-    echo "Deleting vif ${1}..."
-    vif --delete ${1}
+    MONITORING_VIF_ID=${1##vif0/}
+    MONITORING_VIF_ID=${MONITORING_VIF_ID##mon}
+    echo "Deleting vif ${MONITORING_VIF_ID}..."
+    sudo vif --delete ${MONITORING_VIF_ID}
     exit 0
 }
 
@@ -42,43 +44,50 @@ fi
 
 ARG=${1}; shift
 case ${ARG} in
+    "-i" )
+        ARG=${1}
+        shift
+        ;;
     "stop" )
         monitoring_stop ${1};;
 esac
-MONITORED_VIF_ID=${ARG}
+MONITORED_VIF_ID=${ARG##vif0/}
 
 ## check if the monitoring interface is free
 MON_IF_ID=${MONITORED_VIF_ID}
-if ifconfig ${MON_IF_NAME}${MON_IF_ID} &>/dev/null; then
-    error "monitoring interface ${MON_IF_NAME}${MON_IF_ID} is already in use.\nUse ${0##*/} stop ${MONITORED_VIF_ID} to force stop the monitoring."
+if ifconfig ${MON_IF_NAME}${MON_IF_ID} >/dev/null 2>&1; then
+    error "monitoring interface ${MON_IF_NAME}${MON_IF_ID} is already in use.\nUse ${0##*/} stop to force stop the monitoring."
 fi
 
 ## find free monitoring vif index
 MON_VIF_ID=$((${VR_MAX_INTERFACES} - ${MON_IF_ID} - 1))
 while true; do
-    if ! vif --list | grep "^vif0/${MON_VIF_ID}\b" &>/dev/null; then
+    if ! sudo vif --list | grep "^vif0/${MON_VIF_ID}\b" >/dev/null 2>&1; then
         break
     fi
     MON_VIF_ID=$((${MON_VIF_ID} - 1))
 done
 
-vif --add ${MON_IF_NAME}${MON_IF_ID} --type ${MON_TYPE} --vif ${MONITORED_VIF_ID} \
-    --id ${MON_VIF_ID}
+sudo vif --add ${MON_IF_NAME}${MON_IF_ID} --type ${MON_TYPE} \
+    --vif ${MONITORED_VIF_ID} --id ${MON_VIF_ID}
 
 ## wait for monitoring interface to appear
 WAIT=10
-while ! ifconfig ${MON_IF_NAME}${MON_IF_ID} &>/dev/null; do
+while ! ifconfig ${MON_IF_NAME}${MON_IF_ID} >/dev/null 2>&1; do
     WAIT=$((${WAIT} - 1))
     if [ "${WAIT}" = "0" ]; then
         error "no interface ${MON_IF_NAME}${MON_IF_ID}"
     fi
 done
 
-ifconfig ${MON_IF_NAME}${MON_IF_ID} up
+## disable IPv6 on the monitoring interface
+sudo sh -c "echo 1 > /proc/sys/net/ipv6/conf/${MON_IF_NAME}${MON_IF_ID}/disable_ipv6"
+
+sudo ifconfig ${MON_IF_NAME}${MON_IF_ID} up
 
 ## set signal handler
-trap "echo ${0##*/}: deleting vif ${MON_VIF_ID}... && vif --delete ${MON_VIF_ID}" \
-    SIGHUP SIGINT SIGQUIT SIGABRT SIGPIPE SIGTERM
+trap "echo ${0##*/}: deleting vif ${MON_VIF_ID}... && sudo vif --delete ${MON_VIF_ID}" \
+    HUP INT QUIT ABRT PIPE TERM
 
 ## run tcpdump with the rest of arguments
-tcpdump -i ${MON_IF_NAME}${MON_IF_ID} $*
+sudo tcpdump -i ${MON_IF_NAME}${MON_IF_ID} $*
